version : '2'

services: 
    db: 
        build: db/
        restart: unless-stopped
        environment: 
            MYSQL_ONETIME_PASSWORD: "yes"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    web-app:
        depends_on: 
            - db
        build: web-app/
        ports: 
            - "80:80"
        restart: always
        restart: unless-stopped
        environment: 
            DB_HOST: db

